### ISSUE TITLE
please add the following resources

### ISSUE THREAD

**Issue by mjhea0** [hangyan/docker-resources#1]
1. [Docker in Action - Fitter, Happier, More Productive](https://realpython.com/blog/python/docker-in-action-fitter-happier-more-productive/)
2. [Node With Docker - Continuous Integration and Delivery](http://mherman.org/blog/2015/03/06/node-with-docker-continuous-integration-and-delivery)
3. Docker in Action - Development to Delivery: [Part 1](https://blog.rainforestqa.com/2014-11-19-docker-in-action-from-deployment-to-delivery-part-1-local-docker-setup/), [Part 2](https://blog.rainforestqa.com/2014-12-08-docker-in-action-from-deployment-to-delivery-part-2-continuous-integration), [Part 3](https://blog.rainforestqa.com/2015-01-15-docker-in-action-from-deployment-to-delivery-part-3-continuous-delivery)

**Comment by hangyan** [comment]
got it

**Comment by mjhea0** [comment]
Thanks!
